services:
  - type: web
    name: dc-clean-hands-api
    runtime: docker
    plan: starter
    region: oregon
    branch: master
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHONUNBUFFERED
        value: 1
      - key: LOG_LEVEL
        value: INFO
    scaling:
      minInstances: 1
      maxInstances: 1
    disk:
      name: dc-clean-hands-storage
      mountPath: /app/artifacts
      sizeGB: 1